Modules View
TritonSE/LAP-Student-Tracker pull request #109
Opened 2022-10-23 03:02 UTC by nishantbalaji

### Administrative Info

Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Github Issue]-[3-4 word description separated by dashes]`.

### What issue(s) does this branch close?
Closes #101 

### Changes

What changes did you make?
Added a Module view with dropdowns showing the modules

- TODO

### Testing

How did you confirm your changes worked?
Test with dummy data and make sure they displayÍ

- TODO

### Confirmation of Change

Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Module View |
| ----------------------- |
| <img width="1488" alt="image" src="https://user-images.githubusercontent.com/44332326/197371238-0e2e1abb-3e83-4ae2-b6ab-2cc3d6e0e7b2.png">  |

2022-10-31 01:28 UTC, Anshul-Birla reviewed
The styling here has not been applied: 

![image](https://user-images.githubusercontent.com/42627151/198913478-1bfd5222-f204-43bd-a2fa-5fceba2af025.png)

2022-11-06 18:26 UTC, Anshul-Birla requested changes
Some logical changes do need to be made, but i think the overall structure is correct

2022-11-06 18:26 UTC, Anshul-Birla commented on components/SingleClassView/Module/Module.tsx
> +          />
you can make this a popup btw - it doesnt need to be an edit here

2022-11-06 18:26 UTC, Anshul-Birla commented on components/SingleClassView/Module/Module.tsx
> +  const { data: modules, error } = useSWR(`api/class/${id}/modules`, () => api.getClassModules(id));
lets not use swr for this, its probably better to use `useEffect`

2022-11-06 18:26 UTC, Anshul-Birla commented on components/SingleClassView/Module/Module.tsx
> +  const { data: modules, error } = useSWR(`api/class/${id}/modules`, () => api.getClassModules(id));
Take a look at this: https://github.com/TritonSE/WA-Family-Literacy-Application/blob/dc893e77fb15e8ded0a794835f338991b2e96fe3/web/src/pages/UploadBooksPage.tsx#L34

2022-11-06 18:26 UTC, Anshul-Birla commented on context/LeagueAPI.ts
> +  async getModuleItems(moduleId: string): Promise<any> {
reminder to fix the any

2022-11-06 18:26 UTC, Anshul-Birla commented on pages/api/module/[id]/item/[item_id].ts
>          return res.status(StatusCodes.INTERNAL_SERVER_ERROR).json("Internal Server CustomError");
lets remover this custom error and just say internal server error

2022-11-12 20:15 UTC, nishantbalaji commented on components/SingleClassView/Module/Module.tsx
> +const FadeMenu: React.FC<FadeMenuProps> = ({ module, numModules }) => {
ye

2022-11-12 20:18 UTC, nishantbalaji commented on components/SingleClassView/Module/Module.tsx
> +const AccordionLesson = ({ lesson }: { lesson: APIModuleItem }) => {
wait theyre two different things -- lesson is the thing inside the module

2022-11-12 23:57 UTC, Anshul-Birla commented on components/SingleClassView/Module/Module.tsx
> +const AccordionLesson = ({ lesson }: { lesson: APIModuleItem }) => {
lets make it AccordionItem or something - lesson is too constrained of a name

2022-11-20 04:01 UTC, Anshul-Birla requested changes
Some functionality that is currently not working: 
- The image to edit does not show up:  
![image](https://user-images.githubusercontent.com/42627151/202884675-3f7f37e0-58c8-431e-89a0-7567d5f050e2.png)
- When creating a module, the page does not auto-refresh to display the new module. 
- There is some styling issue on the side of the module components
![image](https://user-images.githubusercontent.com/42627151/202884692-7359b2aa-cc27-48d2-afc3-e2b71a54b658.png)
- We shouldn't have borders around these boxes
![image](https://user-images.githubusercontent.com/42627151/202884710-156dc406-135f-4bda-875c-2de4f5f6d9c2.png)
- Hitting the 3 dots causes the entire component to expand. This should not be expected functionality 
- Creating an item does not automatically make it appear in the module dropdown 
- When in the create item page, the "cancel" button causes the module to just move up and down instead of cancelling

2022-11-24 08:42 UTC, nishantbalaji commented
> Some functionality that is currently not working:
> 
> * The image to edit does not show up:
>   ![image](https://user-images.githubusercontent.com/42627151/202884675-3f7f37e0-58c8-431e-89a0-7567d5f050e2.png)
> * When creating a module, the page does not auto-refresh to display the new module.
> * There is some styling issue on the side of the module components
>   ![image](https://user-images.githubusercontent.com/42627151/202884692-7359b2aa-cc27-48d2-afc3-e2b71a54b658.png)
> * We shouldn't have borders around these boxes
>   ![image](https://user-images.githubusercontent.com/42627151/202884710-156dc406-135f-4bda-875c-2de4f5f6d9c2.png)
> * Hitting the 3 dots causes the entire component to expand. This should not be expected functionality
> * Creating an item does not automatically make it appear in the module dropdown
> * When in the create item page, the "cancel" button causes the module to just move up and down instead of cancelling

@Anshul-Birla 

this is mostly fixed, however i need to fix the Vertical Menu toggling the component. I am not sure how to do this with MUI Accordion but I sent you an alternative via slack if that also works?

2022-11-24 23:11 UTC, closed without merging