Feature/zainnk902/class api routes
TritonSE/LAP-Student-Tracker pull request #62
Opened 2022-03-02 05:13 UTC by zainnk902

### Administrative Info

Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Github Issue]-[3-4 word description separated by dashes]`.

### What issue(s) does this branch close?
Closes issue #47 
### Changes

What changes did you make?
- Added Class API, which lets us construct classes in the database, and associate a class ID with an event ID.

### Testing

How did you confirm your changes worked?

- Tested using different scenarios in classes.test.ts, and ran "npm run test"

2022-03-02 21:03 UTC, Anshul-Birla requested changes
Some small changes to be had. Overall, super solid work :)

2022-03-02 22:34 UTC, Anshul-Birla approved these changes
looks great :)

2022-03-03 03:09 UTC, anvitaa22 submitted a review, later dismissed

2022-03-04 23:18 UTC, Anshul-Birla approved these changes
LGTM!

2022-03-04 23:37 UTC, anvitaa22 approved these changes

2022-03-04 23:40 UTC, merged