Feature/allisonbhavsar/52 calendar feed api
TritonSE/LAP-Student-Tracker pull request #63
Opened 2022-03-03 20:01 UTC by allisonbhavsar

### Administrative Info

Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Github Issue]-[3-4 word description separated by dashes]`.

### What issue(s) does this branch close?
Issue #52 

### Changes

What changes did you make?

- Added /api/event-feed/ route to get calendar event feed for a particular user

### Testing

How did you confirm your changes worked?

- Tested with and without specifying userId param
- Tested with invalid date range (start > end)
- Tested with nonexistent userId
- Tested error cases with missing params

### Confirmation of Change

Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

`npm run test`

2022-03-04 23:17 UTC, Anshul-Birla requested changes
Super awesome work getting this all sorted out very quickly. A change that I pointed out - the API is taking the start, end, and userID dates in the query parameters of the call, not the body. I pointed out the changes you need to make for it to all work out :)

2022-03-04 23:17 UTC, Anshul-Birla commented on __test__/event-feed.test.ts
> +  await client.end();
lets delete all the data from tables that you accessed so the next tests are guaranteed to run with a clean db. This wouldn't be an issue if jest ran tests in the same order, but sometimes it doesn't :(

Nishant is currently making a script that will enter a ton of dummy data into the db for our testing purposes :)

2022-03-04 23:17 UTC, Anshul-Birla commented on __test__/event-feed.test.ts
> +    };
Oof, im sorry if i messed up giving this information out. The API takes in nothing in the body. Everything is done via query parameters. So everything is the same, except these should be passed in as the query parameter of  the http request

2022-03-04 23:17 UTC, Anshul-Birla commented on pages/api/event-feed/index.ts
> +  switch (req.method) {
here, `start`, `end` and `userId` will be specified within the query parameters of the request, not the body. Something like this should do the trick:

``` javascript
if (!req.query) {
    return res.status(StatusCodes.INTERNAL_SERVER_ERROR).json("Internal Server Error");
  }

  
  const start = req.query.start as string;
  const end = req.query.end as string;
  const userId = req.query.userId as string;

  if (!start || !end) {
    return res.status(400).json("No start of end date specified");
  }
```

2022-03-04 23:17 UTC, Anshul-Birla reviewed
Just ignore this I forgot to mark the files as viewed lol

2022-03-05 00:58 UTC, Anshul-Birla requested changes

2022-03-05 00:58 UTC, Anshul-Birla commented on lib/database/calendar.ts
>  import { client } from "../db";
Forgot about this. can we put this in calendar-events.ts? That way the file the database functions are in correspond to the route they belong to.

2022-03-06 00:34 UTC, Anshul-Birla approved these changes
I love it! Great work :)

2022-03-06 22:03 UTC, ryanbuui approved these changes
LGTM Nice work!

2022-03-07 01:51 UTC, merged