Availibility API
TritonSE/LAP-Student-Tracker pull request #73
Opened 2022-04-06 18:37 UTC by Anshul-Birla

### Administrative Info

Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Github Issue]-[3-4 word description separated by dashes]`.

### What issue(s) does this branch close?

Closes #8 
Closes #15 

### Changes

Added API route for availabilities. PATCH to /api/availibility/[id] updates a users availibility 
Auto adds a teacher's availability into the database as null when a new teacher is created
Added API route for the calendar to fetch a teacher's availibility while taking into account all commitments that teacher is assigned to

### Testing

How did you confirm your changes worked?

Wrote unit tests

### Confirmation of Change

Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

 - Run npm run test

 Things to note: 
 - Play around with the API to make sure there are no bugs. In particular the availibility-feed API needs another set of eyes

2022-04-07 19:40 UTC, nishantbalaji approved these changes
Functionally looks good, just need to write some comments highlighting what the code does and remove comments that outline TODOs :)

2022-04-07 19:40 UTC, nishantbalaji commented on pages/api/availibility/[id].ts
> +      // todo: validate if id exists
is this done? remove comment if so

2022-04-07 19:40 UTC, nishantbalaji commented on lib/database/availibility-feed.ts
> +// get all intervals with dates
remove comments

2022-04-12 23:28 UTC, allisonbhavsar requested changes
Mostly minor changes, I wasn't sure if line 93 looked right in lib/database/availibility-feed.ts but that could be my misunderstanding (code is very confusing lol). Also spelling of availability in a bunch of places lol

2022-04-12 23:28 UTC, allisonbhavsar commented on lib/database/availibility-feed.ts
> +  const mergedUnavilibilites = Interval.merge(completeUnavailibilites);
lol spelling again

2022-04-12 23:28 UTC, allisonbhavsar commented on lib/database/availibility-feed.ts
> +    mergedUnavilibilites
Are these mergedUnavailabilities guaranteed to be sorted? If not I think that would break calculateBetweenIntervals()

2022-04-12 23:28 UTC, allisonbhavsar commented on lib/database/availibility-feed.ts
> +    if (processedDaysOfWeek.has(weekdayStr) || weekdayStr == "sun") return;
Sorry if I'm misunderstanding the code but why return if "processedDaysOfWeek.has(weekdayStr)"? Do we only want the availability feed for a maximum of one week from the start date parameter?

2022-04-12 23:28 UTC, allisonbhavsar commented on lib/database/users.ts
> +        text: "INSERT INTO availibilities (user_id, time_zone) VALUES ($1, 	$2)",
Is the whitespace here intentional?

2022-04-18 03:10 UTC, Benson272 approved these changes
LGTM

2022-04-18 20:20 UTC, allisonbhavsar approved these changes

2022-04-18 20:40 UTC, merged