Dynamically get all teachers for assigning to a class
TritonSE/LAP-Student-Tracker pull request #81
Opened 2022-04-10 04:31 UTC by Anshul-Birla

### Administrative Info

Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Github Issue]-[3-4 word description separated by dashes]`.

### What issue(s) does this branch close?
Closes #79 
Closes #80 

### Changes

- Added a get route to /api/users that gets all users
- Added a way to filter by role when making get requests
- Added a way to dynamically get all teachers and let users select them 

How did you confirm your changes worked?

- Made multiple teacher accounts and see if making a class with them worked 
- Tested API route with tests

### Confirmation of Change

- Check above

2022-04-17 05:40 UTC, zainnk902 requested changes
Great work! Just had a small change with testing, but everything looks really good.

 One question I had that might just be a design choice but thought I'd mention it; when someone wants to create a class, the dropdown for the teachers available when there are no teachers is just an empty dropdown. There shouldn't be too many cases when there are no teachers, but maybe instead of having an empty dropdown, it just has some error message like "No teachers available"? 

Just a thought, but everything else looked fine.

2022-05-02 04:30 UTC, Anshul-Birla commented
> Great work! Just had a small change with testing, but everything looks really good.
> 
> One question I had that might just be a design choice but thought I'd mention it; when someone wants to create a class, the dropdown for the teachers available when there are no teachers is just an empty dropdown. There shouldn't be too many cases when there are no teachers, but maybe instead of having an empty dropdown, it just has some error message like "No teachers available"?
> 
> Just a thought, but everything else looked fine.

I added some more tests :). 
In the real app, there are not going to be any cases where there are no teachers so i don't think its super necessary for the create class modal to have a no teachers view :). Thanks for the idea though :)

2022-05-03 23:42 UTC, allisonbhavsar requested changes
Looks good, just left a couple of comments about the role query param in the GET route for all users

2022-05-03 23:42 UTC, allisonbhavsar commented on pages/api/users/index.ts
> +      if (req.query && req.query.role) role = req.query.role as Roles;
Should the GET route return 400 bad request error if the "role" query param is invalid (i.e. not one of Admin/Volunteer/Student/Staff/Parent)? Currently it returns an empty array on an invalid query param with status code 200

2022-05-03 23:42 UTC, allisonbhavsar commented on __tests__/users.test.ts
> +
Add a test case where the value of the role query param is an invalid Role? Although I'm not sure what you want the expected behavior to be in this case, I made another comment about this in pages/api/users/index.ts

2022-05-04 12:05 UTC, zainnk902 approved these changes
lgtm 🤝

2022-05-06 23:09 UTC, allisonbhavsar approved these changes
LGTM

2022-05-06 23:11 UTC, merged