Feature/anshul birla/88 authenticated api
TritonSE/LAP-Student-Tracker pull request #91
Opened 2022-05-15 05:40 UTC by Anshul-Birla

### Administrative Info

Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Github Issue]-[3-4 word description separated by dashes]`.

### What issue(s) does this branch close?

### Changes

What changes did you make?

- TODO

### Testing

How did you confirm your changes worked?

- TODO

### Confirmation of Change

Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
| ----------------------- |
| [TODO Screenshot Link]  |

2022-05-17 22:22 UTC, Benson272 commented on components/Profile/AdminTeacherProfile/ProfileViewLeft.tsx
> +const ProfilePicture: React.FC<ProfilePictureProps> = ({
Maybe have some way to indicate that the pfp is clickable/editable after clicking the edit button

2022-05-19 21:04 UTC, allisonbhavsar requested changes
Looks great! Just left a few minor suggestions and was also wondering if the client cares about being able to remove a profile pic?

2022-05-19 21:04 UTC, allisonbhavsar commented on context/AuthContext.tsx
> +  // getNewRefreshToken: () => {
Did you mean to leave the commented code in this file?

2022-05-23 05:21 UTC, Benson272 approved these changes
lgtm

2022-05-23 05:48 UTC, allisonbhavsar approved these changes
LGTM, just left one comment about commented out css styles

2022-05-23 05:48 UTC, allisonbhavsar commented on components/Profile/AdminTeacherProfile/ProfileViewRight.module.css
> +  /*justify-content: space-between;*/
did you mean to leave this?

2022-05-23 06:57 UTC, Anshul-Birla commented on components/Profile/AdminTeacherProfile/ProfileViewRight.module.css
> +  /*justify-content: space-between;*/
ah good check ty

2022-05-23 06:59 UTC, merged